"""Art generation orchestration for pixel-art and half-block modes."""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from PIL import Image

from tpet.art.storage import (
    get_art_dir,
    save_halfblock_frame,
    save_png_frame,
    save_prompt,
)
from tpet.art.storage import (
    sanitize_name as _sanitize_name,
)

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

    from tpet.art.openai_client import GenerationResult
    from tpet.config import TpetConfig
    from tpet.models.pet import PetProfile

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Sprite prompts
# ---------------------------------------------------------------------------


def _sprite_layout_instructions() -> str:
    """Return the frame layout and style instructions appended to all prompts.

    These instructions describe the 2x3 sprite sheet format and technical
    requirements for proper frame splitting. They are always included,
    regardless of any user-provided prompt override.

    Returns:
        Frame layout and style instruction string.
    """
    return (
        "Layout: 2 columns x 3 rows grid (6 panels). The overall image must be portrait orientation "
        "(taller than wide, approximately 2:3 aspect ratio). "
        "Each panel shows a different animation frame:\n"
        "- Row 1, Left: Idle pose (relaxed, eyes fully open)\n"
        "- Row 1, Right: Idle shift (slight pose variation, eyes fully open)\n"
        "- Row 2, Left: BLINK — pixel-for-pixel IDENTICAL to Row 1 Left (same body, same size, "
        "same position, same colors, same outline) with ONE change: the eyes are closed "
        "(same closed-eye style as the sleeping frame). Nothing else changes.\n"
        "- Row 2, Right: BLINK — pixel-for-pixel IDENTICAL to Row 1 Right (same body, same size, "
        "same position, same colors, same outline) with ONE change: the eyes are closed "
        "(same closed-eye style as the sleeping frame). Nothing else changes.\n"
        "- Row 3, Left: Surprised/reacting (eyes wide, mouth open)\n"
        "- Row 3, Right: Sleeping (eyes closed, zzz bubbles)\n\n"
        "Style: Clean pixel art, cute and charming, suitable for a terminal pet. "
        "The creature must look identical across all 6 frames (same proportions, colors, style). "
        "Only the expression and small pose details should differ between frames.\n\n"
        "The creature MUST have a thick black outline around the entire body and all major features. "
        "NO shadows, NO drop shadows, NO ambient occlusion. "
        "Flat solid colors only with bold black outlines."
    )


def _sprite_layout_instructions_10(pet: PetProfile) -> str:
    """Return the 10-frame (2 cols x 5 rows) layout instructions for macos-desktop mode.

    Walk / fall / landing rows are filled in from the pet's per-creature
    locomotion descriptors (``body_plan``, ``walk_description``,
    ``fall_description``, ``landing_description``) generated by the profile
    LLM, so a 4-legged cat, a centipede, a snail, and a balloon each get
    body-appropriate frames instead of a single hardcoded rule.
    """
    body_plan = pet.body_plan.strip() or f"a {pet.creature_type}"
    walk = pet.walk_description.strip() or (
        "Two-stride walk cycle facing right; pose A and pose B differ in stride only, "
        "no horizontal mirroring."
    )
    fall = pet.fall_description.strip() or (
        "Airborne with limbs splayed and a startled expression — no ground under it."
    )
    landing = pet.landing_description.strip() or (
        "Dazed on the ground: eyes as two small X shapes, 2-3 small yellow stars around its head, "
        "mouth slightly open."
    )

    return (
        "CRITICAL FORMATTING RULES (read these first):\n"
        "1. NO GRID LINES, NO BORDERS, NO PANEL OUTLINES, NO FRAME SEPARATORS, NO DIVIDERS. "
        "The 10 cells must be visually contiguous — only the magenta background and the "
        "characters appear. Do NOT draw any line, stroke, or border between cells.\n"
        "2. NO LABELS, NO TEXT, NO ROW/COLUMN NUMBERS, NO CAPTIONS anywhere on the image.\n"
        "3. The character MUST appear at the SAME SIZE in every cell — same body proportions, "
        "same scale, same number of pixels tall and wide. Do NOT zoom in for some frames or "
        "out for others. The bounding box of the character should be roughly identical across "
        "all 10 cells.\n"
        "4. Center the character horizontally within its cell, with consistent vertical placement "
        "(idle/walk: feet near the cell bottom; fall: mid-cell; landing: floor of the cell).\n\n"
        "Layout: 2 columns x 5 rows grid (10 panels). The overall image must be portrait "
        "orientation (taller than wide, approximately 2:5 aspect ratio). "
        f"The character has this anatomy: {body_plan}. Use this body plan consistently across "
        "every cell.\n"
        "Each panel shows a different animation frame:\n"
        "- Row 1, Left: Idle pose (relaxed, eyes fully open, on the ground)\n"
        "- Row 1, Right: Idle shift (same pose with tiny body/head tilt, eyes fully open)\n"
        "- Row 2, Left: BLINK — pixel-for-pixel IDENTICAL to Row 1 Left (same body, same size, "
        "same position, same colors, same outline) with ONE change: the eyes are closed "
        "(same closed-eye style as the sleeping frame). Nothing else changes.\n"
        "- Row 2, Right: BLINK — pixel-for-pixel IDENTICAL to Row 1 Right (same body, same size, "
        "same position, same colors, same outline) with ONE change: the eyes are closed "
        "(same closed-eye style as the sleeping frame). Nothing else changes.\n"
        "- Row 3, Left: Excited / surprised — eyes wide open, mouth open in a happy or "
        "startled expression. Same body and colors as idle.\n"
        "- Row 3, Right: Sleeping — eyes closed, tiny zzz bubbles above the head. "
        "The character may lay down if it fits the description.\n"
        f"- Row 4, Left: Walk stride A. {walk} Eyes open, FACING TO THE RIGHT.\n"
        "- Row 4, Right: Walk stride B — FACING TO THE RIGHT, the SAME direction as Row 4 Left. "
        "Do NOT flip or mirror the character horizontally. This is the mid-stride pose where the "
        "legs CROSS each other as they pass: limbs on opposite sides of the body swap which is "
        "forward, so only ONE leg per side is visible (the others are hidden behind the body). "
        "For creatures with many legs, show the wave pattern at its crossover point. For wingless "
        "or legless locomotion (slither, hover, slide), show the alternate phase of the same cycle.\n"
        f"- Row 5, Left: Falling. {fall} Keep the same character, same size, same style, same colors.\n"
        f"- Row 5, Right: Landing. {landing} Keep the same character, same colors, same style.\n"
        "\n"
        "Style: Clean pixel art, cute and charming, suitable for a terminal pet. "
        "The creature must look identical across all frames (same proportions, colors, style). "
        "Only the expression and pose should differ between frames.\n\n"
        "The creature MUST have a thick black outline around the entire body and all major features. "
        "NO shadows, NO drop shadows, NO ambient occlusion. "
        "Flat solid colors only with bold black outlines."
        "\n\n"
        "IMPORTANT:\n"
        "NO LABELS\n"
        "Don't label the generated image or the individual frames\n"
        "Don't separate the individual frames at all -- no outline, no grid"
    )


def build_sprite_prompt_10(pet: PetProfile, prompt_override: str = "") -> str:
    """Build the prompt for generating a 2x5 (10-frame) sprite sheet with chroma key background.

    Used when art is being generated for ``art_mode = macos-desktop``. Same
    background rules as :func:`build_sprite_prompt` (magenta chroma key for
    Gemini) but with the extended 10-frame layout.
    """
    subject = prompt_override.strip() if prompt_override.strip() else _default_subject(pet)
    return (
        f"{subject}\n\n"
        f"{_sprite_layout_instructions_10(pet)}\n\n"
        "Clean edges, no anti-aliasing into background.\n\n"
        "CRITICAL: The background MUST be solid pure magenta #FF00FF RGB(255,0,255) "
        "with absolutely no gradients, no shadows, no shading, no variations. "
        "A single flat magenta color across the entire background. "
        "Isolated subject, centered composition within each cell. "
        "This is essential for automated background removal processing."
    )


def _default_subject(pet: PetProfile) -> str:
    """Return the default subject description from pet profile data.

    Args:
        pet: Pet profile with creature info.

    Returns:
        Subject description string.
    """
    return (
        f"Create a pixel art sprite sheet of a {pet.creature_type} named {pet.name}. "
        f"Personality: {pet.personality}. "
        f"Rarity: {pet.rarity.value}."
    )


def build_sprite_prompt(pet: PetProfile, prompt_override: str = "") -> str:
    """Build the prompt for generating a 2x3 sprite sheet with chroma key background.

    For use with Gemini (no native transparency). Requests solid magenta
    background for automated chroma key removal.

    If prompt_override is provided, it replaces the default subject description
    but the frame layout instructions and background requirements are always appended.

    Args:
        pet: Pet profile with creature info.
        prompt_override: Custom prompt to use instead of auto-generated subject.

    Returns:
        Prompt string for Gemini image generation.
    """
    subject = prompt_override.strip() if prompt_override.strip() else _default_subject(pet)
    return (
        f"{subject}\n\n"
        f"{_sprite_layout_instructions()}\n\n"
        "Clean edges, no anti-aliasing into background.\n\n"
        "CRITICAL: The background MUST be solid pure magenta #FF00FF RGB(255,0,255) "
        "with absolutely no gradients, no shadows, no shading, no variations. "
        "A single flat magenta color across the entire background. "
        "Isolated subject, centered composition. "
        "This is essential for automated background removal processing."
    )


def build_openai_sprite_prompt(pet: PetProfile, prompt_override: str = "") -> str:
    """Build the prompt for generating a 2x3 sprite sheet with transparent background.

    For use with OpenAI (native transparency support, no chroma key needed).
    Legacy: used when generating all frames in a single call.

    If prompt_override is provided, it replaces the default subject description
    but the frame layout instructions are always appended.

    Args:
        pet: Pet profile with creature info.
        prompt_override: Custom prompt to use instead of auto-generated subject.

    Returns:
        Prompt string for OpenAI image generation.
    """
    subject = prompt_override.strip() if prompt_override.strip() else _default_subject(pet)
    return (
        f"{subject}\n\n"
        f"{_sprite_layout_instructions()}\n\n"
        "The background must be completely transparent. "
        "Do NOT add any background color, gradient, or fill. "
        "The subject must be isolated with clean pixel-perfect edges."
    )


# ---------------------------------------------------------------------------
# Per-frame prompts for OpenAI multi-call pipeline
# ---------------------------------------------------------------------------

_STYLE_SUFFIX = (
    "Clean pixel art style with thick black outlines around the entire body "
    "and all major features. Flat solid colors, no shadows, no gradients, "
    "no glow, no drop shadow, no ambient occlusion. "
    "The background MUST be completely empty and transparent — no color, "
    "no vignette, no radial gradient, no gray, nothing behind the character."
)


def _build_base_frame_prompt(pet: PetProfile, prompt_override: str = "") -> str:
    """Build prompt for generating the canonical idle frame.

    Args:
        pet: Pet profile with creature info.
        prompt_override: Custom prompt override.

    Returns:
        Prompt string for the base idle frame.
    """
    if prompt_override.strip():
        subject = prompt_override.strip()
    else:
        subject = (
            f"A single pixel art character: a {pet.creature_type} named {pet.name}. "
            f"Personality: {pet.personality}. Rarity: {pet.rarity.value}."
        )
    return f"{subject}\n\nIdle pose, relaxed, eyes fully open. Centered in the frame.\n\n{_STYLE_SUFFIX}"


# Edit prompts: each describes ONLY the change from the base idle frame.
# input_fidelity="high" handles keeping everything else identical.
# Blink frames (2, 3) are NOT generated via AI — they are created
# programmatically by compositing closed-eye pixels from the sleep frame
# onto the idle frames. This avoids the OpenAI edit API introducing
# unwanted variation (different backgrounds, proportions, colors).
_EDIT_PROMPTS: dict[int, tuple[str, str]] = {
    1: (
        "idle-shift",
        "Make a very subtle pose variation — tilt the head or body very slightly. "
        "Keep the same character, same size, same position, same colors. Eyes stay open.",
    ),
    4: (
        "react",
        "Make the character look surprised — widen the eyes and open the mouth. "
        "Keep the same character, same size, same position, same colors.",
    ),
    5: (
        "sleep",
        "Make the character look like it's sleeping — close the eyes and add small zzz bubbles. "
        "Keep the same character, same size, same position, same colors.",
    ),
}


# Edit prompts for the 10-frame macos-desktop layout. Includes the 6-frame
# entries plus walk-a, walk-b, fall, and stunned. Frames 2 and 3 remain
# programmatic blink composites (not listed here).
_EDIT_PROMPTS_10: dict[int, tuple[str, str]] = {
    **_EDIT_PROMPTS,
    6: (
        "walk-a",
        "Make the character look like it's mid-step walking — front foot planted "
        "on the ground, back foot lifted slightly off the ground. Body leaning very "
        "slightly forward. Facing to the right. Eyes stay open. Keep the same "
        "character, same size, same style, same colors.",
    ),
    7: (
        "walk-b",
        "Make the character look like it's mid-step in the alternate stride. "
        "IMPORTANT: the character must be FACING TO THE RIGHT — the SAME direction "
        "as the previous walk frame. Do NOT flip or mirror the character "
        "horizontally. Only the legs change: the back foot is now planted on the "
        "ground, and the front foot is lifted and extended forward. Eyes stay open. "
        "Keep the same character, same size, same style, same colors.",
    ),
    8: (
        "fall",
        "Make the character look like it's falling through the air, no ground under its feet. "
        "- If the creature has wings or can fly (bird, dragon, cloud, fairy, bat, baloon, etc.), "
        "show it gliding calmly downward with wings spread wide and a composed expression, "
        "looking toward the ground below. "
        "- If the character cannot fly, show it limbs splayed outward in a startled posture "
        "and mouth open in surprise. "
        "Keep the same character, same size, same style, same colors.",
    ),
    9: (
        "landed",
        "Make the character look like it is landing in a way that matches its body:\n"
        "- If it can fly (e.g. has wings, bird, dragon, fairy, bat, etc.): landed neatly on the ground with wings folded "
        "against its body and a neutral settled expression (not dazed).\n"
        "- If squishy or gooey (e.g., blob, slime, jelly, etc.): SPLATTED into a flat puddle, "
        "body flattened and spreading outward with a few droplets splashing to the sides.\n"
        "- If brittle or crystalline (crystal, glass, shell, rock, etc.): SHATTERED into five "
        "angular shards scattered around the landing spot, with small crack lines.\n"
        "- If metallic or mechanical (robot, tin): dented and/or short-circuiting on the "
        "ground with small black smoke puffs and a few yellow spark shapes around it.\n"
        "- In all other cases: dazed — body on or near the ground, eyes as two small X shapes, "
        "2–3 small yellow star shapes floating around its head, mouth slightly open.\n"
        "Keep the same character, same colors, same style.",
    ),
}


# ---------------------------------------------------------------------------
# Gemini generators (with chroma key)
# ---------------------------------------------------------------------------


def _generate_gemini_sprite_frames(config: TpetConfig, pet: PetProfile) -> tuple[list[Image.Image], Path]:
    """Generate and split a Gemini sprite sheet into individual frame images.

    Shared helper for the Gemini pixel-art and half-block pipelines.
    Handles API call, PNG save, sprite splitting, and per-frame PNG storage.

    Steps:
    1. Build prompt and generate sprite sheet via Gemini
    2. Split the sheet into individual frames (2x3 or 2x2 layout)
    3. Save each frame as a full-resolution PNG for runtime scaling

    Args:
        config: Application configuration.
        pet: Pet profile.

    Returns:
        Tuple of (list of PIL frame Images, Path to the sprite sheet PNG).

    Raises:
        RuntimeError: If the Gemini API call fails.
        OSError: If the sprite file cannot be read.
    """
    from tpet.art.client import GeminiImageClient
    from tpet.art.process import create_blink_frame, crop_frames_to_common_bbox, split_sprite_sheet

    art_dir = get_art_dir(config.pet_data_dir)
    sprite_path = art_dir / f"{_sanitize_name(pet.name)}_sprite.png"

    resolved = config.resolved_image_art_provider
    client = GeminiImageClient(model=resolved.model, api_key=resolved.api_key)
    prompt = build_sprite_prompt(pet, prompt_override=config.art_prompt)
    save_prompt(config.pet_data_dir, pet.name, prompt)
    logger.debug("=== Gemini sprite prompt (6-frame sheet) ===\n%s\n=== end prompt ===", prompt)
    client.generate_sprite(
        prompt=prompt,
        output_path=sprite_path,
        aspect_ratio="2:3",
        resolution="1k",
    )

    sprite = Image.open(sprite_path)
    logger.debug("Sprite sheet loaded: %dx%d", sprite.width, sprite.height)

    frames = split_sprite_sheet(sprite)
    logger.debug("Split into %d frames", len(frames))

    # Replace AI-generated blink frames with programmatic composites
    # for consistent eye-closed animation (AI blink frames have too much variation)
    if len(frames) >= 6:
        sleep_frame = frames[5]
        frames[2] = create_blink_frame(frames[0], sleep_frame)
        frames[3] = create_blink_frame(frames[1], sleep_frame)
        logger.info("Replaced blink frames 2,3 with programmatic composites from idle+sleep")

    # Crop all frames to a shared union bbox so every frame has identical
    # dimensions — keeps the character position stable across frames and
    # strips the empty margins the LLM leaves around the subject.
    frames = crop_frames_to_common_bbox(frames)
    if frames:
        logger.debug("Union-cropped frames to %dx%d", frames[0].width, frames[0].height)

    # Save raw PNG frames at full resolution for runtime scaling
    for i, frame in enumerate(frames):
        save_png_frame(config.pet_data_dir, pet.name, i, frame)

    return frames, sprite_path


def _generate_gemini_sprite_frames_10(config: TpetConfig, pet: PetProfile) -> tuple[list[Image.Image], Path]:
    """Generate and split a 10-frame (2x5) Gemini sprite sheet for macos-desktop mode.

    Uses the extended :func:`build_sprite_prompt_10` prompt and a taller
    aspect ratio (9:16 — the tallest portrait Gemini supports; 2:5 is not
    supported by the API). Splits via ``split_sprite_sheet`` which
    auto-detects the 2x5 layout by aspect ratio.
    """
    from tpet.art.client import GeminiImageClient
    from tpet.art.process import remove_chroma_key, split_sprite_sheet

    art_dir = get_art_dir(config.pet_data_dir)
    sprite_path = art_dir / f"{_sanitize_name(pet.name)}_sprite.png"

    resolved = config.resolved_image_art_provider
    client = GeminiImageClient(model=resolved.model, api_key=resolved.api_key)
    prompt = build_sprite_prompt_10(pet, prompt_override=config.art_prompt)
    save_prompt(config.pet_data_dir, pet.name, prompt)
    logger.debug("=== Gemini sprite prompt (10-frame sheet) ===\n%s\n=== end prompt ===", prompt)
    client.generate_sprite(
        prompt=prompt,
        output_path=sprite_path,
        aspect_ratio="9:16",
        resolution="1k",
    )

    sprite = Image.open(sprite_path)
    logger.debug("Sprite sheet loaded (10-frame): %dx%d", sprite.width, sprite.height)

    frames = split_sprite_sheet(sprite, layout="2x5", inset_px=6)
    logger.debug("Split into %d frames", len(frames))
    if len(frames) != 10:
        raise RuntimeError(
            f"Expected 10-frame sprite sheet for macos-desktop, got {len(frames)} frames. "
            f"Sprite was {sprite.width}x{sprite.height}."
        )

    # Strip magenta chroma background from each cell. No compositing or
    # union-bbox cropping — every frame is the AI-generated cell as-is, with
    # transparent background. Bias detection toward pure magenta so frames
    # where the cat touches a cell edge don't pick up the black outline as
    # the bg color, and use a generous tolerance to catch antialiased fringes.
    chroma_target = (255, 0, 255)
    chroma_tolerance = max(config.chroma_tolerance, 100)
    frames = [
        remove_chroma_key(f, tolerance=chroma_tolerance, target_color=chroma_target)
        for f in frames
    ]

    for i, frame in enumerate(frames):
        save_png_frame(config.pet_data_dir, pet.name, i, frame)

    return frames, sprite_path


def generate_macos_desktop_art_openai(
    config: TpetConfig,
    pet: PetProfile,
    on_progress: Callable[[int, int, str], None] | None = None,
    base_image_path: Path | None = None,
) -> tuple[list[str], GenerationResult | None]:
    """Generate the 10 PNG frames for macos-desktop via OpenAI/OpenRouter.

    Uses the parameterized OpenAI pipeline with :data:`_EDIT_PROMPTS_10`
    (adds walk-a, walk-b, fall, stunned to the existing idle-shift/react/sleep
    edits). Frames 2 and 3 remain programmatic blink composites.

    Saves each frame as ``{pet_name}_frame_{N}.png`` via save_png_frame — the
    OpenAI path already writes to those paths during the edit loop, but we
    save again to be consistent with the Gemini path.

    Returns the list of saved PNG paths (as strings) so callers can detect
    success and report the frame count.
    """
    frames, result = _generate_openai_frames(
        config,
        pet,
        on_progress=on_progress,
        base_image_path=base_image_path,
        edit_prompts=_EDIT_PROMPTS_10,
        frame_count=10,
    )

    # Frames are already on disk (the edit loop writes each one). Re-save to
    # be explicit, matching the Gemini path's behavior.
    paths: list[str] = []
    for i, frame in enumerate(frames):
        path = save_png_frame(config.pet_data_dir, pet.name, i, frame)
        paths.append(str(path))

    return paths, result


def generate_macos_desktop_art(
    config: TpetConfig,
    pet: PetProfile,
    on_progress: Callable[[int, int, str], None] | None = None,
    base_image_path: Path | None = None,
) -> tuple[list[str], GenerationResult | None]:
    """Generate the 10 PNG frames required by art_mode=macos-desktop.

    Routes to the Gemini sprite-sheet pipeline or the OpenAI edit pipeline
    based on the configured image art provider. Returns empty art-strings —
    the desktop pet consumes raw PNGs, not half-block text.
    """
    from tpet.art.openai_client import GenerationResult  # noqa: F401  # re-exported for type
    from tpet.config import LLMProvider

    resolved = config.resolved_image_art_provider

    if resolved.provider == LLMProvider.GEMINI:
        if base_image_path is not None:
            raise ValueError(
                "--base-image is not supported for macos-desktop with Gemini. "
                "Use OpenAI/OpenRouter provider if you need to supply your own idle frame."
            )
        _generate_gemini_sprite_frames_10(config, pet)
        return [], None

    if resolved.provider in (LLMProvider.OPENAI, LLMProvider.OPENROUTER):
        return generate_macos_desktop_art_openai(config, pet, on_progress=on_progress, base_image_path=base_image_path)

    raise ValueError(
        f"macos-desktop art generation is not supported for provider "
        f"{resolved.provider.value}. Use 'gemini', 'openai', or 'openrouter'."
    )


def _process_frames(
    frames: list[Image.Image],
    config: TpetConfig,
    pet_name: str,
    resize_fn: Callable[[Image.Image, int], Image.Image],
    target_height: int,
    convert_fn: Callable[[Image.Image], str],
    save_fn: Callable[[Path, str, int, str], Path] | None,
    label: str,
    chroma_key: bool = False,
    save_png: bool = False,
) -> list[str]:
    """Shared pipeline: resize -> optional chroma key -> convert -> save for each frame.

    Args:
        frames: Source PIL images.
        config: Application configuration.
        pet_name: Pet name for storage.
        resize_fn: Function to resize a frame (takes image and target_height).
        target_height: Target pixel height for resizing.
        convert_fn: Function to convert a PIL image to a text string.
        save_fn: Function to save a text frame (config_dir, pet_name, index, data), or None to skip.
        label: Human-readable frame type for logging.
        chroma_key: Whether to apply chroma key background removal after resize.
        save_png: Whether to also save source frames as raw PNGs.

    Returns:
        List of converted frame strings.
    """
    from tpet.art.process import remove_chroma_key

    output_frames: list[str] = []
    for i, frame in enumerate(frames):
        if save_png:
            save_png_frame(config.pet_data_dir, pet_name, i, frame)
        resized = resize_fn(frame, target_height)
        if chroma_key:
            resized = remove_chroma_key(resized, tolerance=config.chroma_tolerance)
        frame_data = convert_fn(resized)
        output_frames.append(frame_data)
        if save_fn:
            save_fn(config.pet_data_dir, pet_name, i, frame_data)
        logger.debug("%s frame %d: %dx%d -> %d chars", label, i, resized.width, resized.height, len(frame_data))
    return output_frames


def generate_halfblock_art(config: TpetConfig, pet: PetProfile) -> list[str]:
    """Generate half-block art frames via Gemini with chroma key removal.

    Args:
        config: Application configuration.
        pet: Pet profile.

    Returns:
        List of half-block strings (one per frame), or empty list on failure.
    """
    from tpet.art.process import image_to_halfblock, resize_for_halfblock

    logger.info("Generating halfblock sprite sheet for %s via Gemini", pet.name)
    frames, _ = _generate_gemini_sprite_frames(config, pet)
    return _process_frames(
        frames,
        config,
        pet.name,
        resize_fn=resize_for_halfblock,
        target_height=config.halfblock_size,
        convert_fn=image_to_halfblock,
        save_fn=save_halfblock_frame,
        label="Halfblock",
        chroma_key=True,
    )


# ---------------------------------------------------------------------------
# OpenAI generators (multi-call with edit for consistency)
# ---------------------------------------------------------------------------


def _generate_openai_frames(
    config: TpetConfig,
    pet: PetProfile,
    on_progress: Callable[[int, int, str], None] | None = None,
    base_image_path: Path | None = None,
    *,
    edit_prompts: dict[int, tuple[str, str]] = _EDIT_PROMPTS,
    frame_count: int = 6,
) -> tuple[list[Image.Image], GenerationResult]:
    """Generate individual frames via OpenAI: base generate + edits + programmatic blinks.

    Uses images.generate for the base idle frame, then images.edit with
    input_fidelity="high" for each variant in ``edit_prompts``. Blink frames
    (2, 3) are always created programmatically by compositing closed-eye pixels
    from the sleep frame onto the idle frames.

    When ``base_image_path`` is provided, it is used as the idle frame directly,
    skipping generation and cleanup steps.

    Defaults (``edit_prompts=_EDIT_PROMPTS``, ``frame_count=6``) produce the
    canonical 6-frame sprite. Pass ``edit_prompts=_EDIT_PROMPTS_10`` and
    ``frame_count=10`` for the macos-desktop layout.

    Args:
        config: Application configuration.
        pet: Pet profile.
        on_progress: Optional callback(current, total, label) for progress updates.
        base_image_path: Optional path to a user-provided idle frame image.
        edit_prompts: Mapping of target frame index -> (label, edit prompt).
        frame_count: Number of frames to assemble in the returned list.

    Returns:
        Tuple of (list of PIL Images in order, GenerationResult with usage stats).

    Raises:
        RuntimeError: If any API call fails.
    """
    from pathlib import Path as _Path

    from tpet.art.openai_client import GenerationResult, ImageUsage, OpenAIImageClient
    from tpet.art.process import create_blink_frame

    result = GenerationResult()
    total_usage = ImageUsage()
    art_dir = get_art_dir(config.pet_data_dir)
    safe_name = _sanitize_name(pet.name)
    resolved = config.resolved_image_art_provider
    client = OpenAIImageClient(model=resolved.model, api_key=resolved.api_key, base_url=resolved.base_url or None)

    if base_image_path is not None:
        # Use the user-provided image as frame 0 — skip generation and cleanup
        # +len for variant edits, +1 for blink compositing
        total_steps = len(edit_prompts) + 1

        def _report(current: int, label: str) -> None:
            if on_progress:
                on_progress(current, total_steps, label)

        base_path = _Path(base_image_path)
        # Copy the user image into the art dir as frame 0
        frame_0_path = art_dir / f"{safe_name}_frame_0.png"
        user_image = Image.open(base_path).convert("RGBA")
        user_image.save(frame_0_path, format="PNG")
        logger.info("Using user-provided base image: %s (%dx%d)", base_path, user_image.width, user_image.height)
        ai_frames: dict[int, Image.Image] = {0: user_image}
    else:
        # +1 for generate, +1 for cleanup edit, +len for variant edits, +1 for blink compositing
        total_steps = 2 + len(edit_prompts) + 1

        def _report(current: int, label: str) -> None:
            if on_progress:
                on_progress(current, total_steps, label)

        frame_0_path = art_dir / f"{safe_name}_frame_0.png"
        if frame_0_path.exists():
            # Resume: frame 0 already on disk from a prior run.
            _report(1, "idle (cached)")
            _report(2, "idle (cached)")
            logger.info("Frame 0 already exists at %s, skipping generate + cleanup", frame_0_path)
            ai_frames = {0: Image.open(frame_0_path)}
        else:
            # Step 1: Generate the initial base idle frame
            _report(1, "idle (generate)")
            base_prompt = _build_base_frame_prompt(pet, prompt_override=config.art_prompt)
            save_prompt(config.pet_data_dir, pet.name, base_prompt)
            raw_base_path = art_dir / f"{safe_name}_frame_0_raw.png"
            logger.info("Generating base idle frame for %s via OpenAI", pet.name)
            logger.debug("=== OpenAI base idle prompt ===\n%s\n=== end prompt ===", base_prompt)
            _, usage = client.generate_sprite(
                prompt=base_prompt,
                output_path=raw_base_path,
                size="1024x1024",
                quality="medium",
            )
            total_usage += usage
            result.api_calls += 1

            # Step 2: Clean up the base frame via edit to fix background transparency
            _report(2, "idle (cleanup)")
            logger.info("Cleaning up base frame background via edit")
            cleanup_prompt = (
                "Keep this pixel art character EXACTLY as it is — same pose, same colors, "
                "same details, same size, same position, same thick black outline, same "
                "eyes, same mouth, same face. Change nothing about the character itself. "
                "ONLY the empty area around the character (the outer background fill) "
                "should become transparent. Do NOT make any part of the character — body, "
                "outline, eyes, or features — transparent. Every pixel of the character "
                "must remain fully OPAQUE. Only the space surrounding the character "
                "becomes transparent."
            )
            logger.debug("=== OpenAI cleanup edit prompt ===\n%s\n=== end prompt ===", cleanup_prompt)
            _, usage = client.edit_sprite(
                image_path=raw_base_path,
                prompt=cleanup_prompt,
                output_path=frame_0_path,
                quality="medium",
            )
            total_usage += usage
            result.api_calls += 1

            ai_frames = {0: Image.open(frame_0_path)}

    # frame_0_path is the canonical idle frame used as input for all edits
    edit_source = frame_0_path
    logger.debug("Base frame 0 (idle): %dx%d", ai_frames[0].width, ai_frames[0].height)

    # Edit the base frame for each variant. For 6-frame: 1=idle-shift, 4=react,
    # 5=sleep. For 10-frame: plus 6=walk-a, 7=walk-b, 8=fall, 9=stunned.
    # Step numbering starts after the base image steps (1 if user-provided, 3 if generated).
    edit_step_start = 1 if base_image_path is not None else 3
    opacity_guard = (
        " IMPORTANT: every shape must have its own thick black outline. No pixel "
        "inside any drawn shape may be transparent — every pixel inside "
        "a shape is fully OPAQUE. If you are unsure what color a pixel inside a "
        "shape should be, fill it with solid white rather than leaving it "
        "transparent."
    )
    for step, frame_idx in enumerate(sorted(edit_prompts.keys()), start=edit_step_start):
        label, edit_prompt = edit_prompts[frame_idx]
        out_path = art_dir / f"{safe_name}_frame_{frame_idx}.png"
        if out_path.exists():
            # Resume: frame already on disk from a prior run.
            _report(step, f"{label} (cached)")
            logger.info("Frame %d (%s) already exists, skipping", frame_idx, label)
            ai_frames[frame_idx] = Image.open(out_path)
            continue
        _report(step, label)
        logger.info("Generating frame %d (%s) via OpenAI edit", frame_idx, label)
        full_edit_prompt = edit_prompt + opacity_guard
        logger.debug(
            "=== OpenAI edit prompt for frame %d (%s) ===\n%s\n=== end prompt ===",
            frame_idx, label, full_edit_prompt,
        )
        _, usage = client.edit_sprite(
            image_path=edit_source,
            prompt=full_edit_prompt,
            output_path=out_path,
            quality="medium",
        )
        total_usage += usage
        result.api_calls += 1
        frame = Image.open(out_path)
        ai_frames[frame_idx] = frame
        logger.debug("Frame %d (%s): %dx%d", frame_idx, label, frame.width, frame.height)

    # Step 4: Create blink frames programmatically from idle + sleep
    _report(total_steps, "blink (compositing)")
    sleep_frame = ai_frames[5]

    # Frame 2: blink = idle body + closed eyes from sleep
    blink_0 = create_blink_frame(ai_frames[0], sleep_frame)
    blink_0_path = art_dir / f"{safe_name}_frame_2.png"
    blink_0.save(blink_0_path, format="PNG")
    ai_frames[2] = blink_0
    logger.info("Created blink frame 2 via compositing from idle + sleep")

    # Frame 3: blink-shift = idle-shift body + closed eyes from sleep
    blink_1 = create_blink_frame(ai_frames[1], sleep_frame)
    blink_1_path = art_dir / f"{safe_name}_frame_3.png"
    blink_1.save(blink_1_path, format="PNG")
    ai_frames[3] = blink_1
    logger.info("Created blink frame 3 via compositing from idle-shift + sleep")

    # Assemble in order: 0, 1, 2, 3, ..., frame_count - 1
    frames = [ai_frames[i] for i in range(frame_count)]

    # Crop all frames to a shared union bbox so every frame has identical
    # dimensions — keeps the character position stable across frames and
    # strips the empty margins the edit API leaves around the subject.
    # Rewrite the on-disk PNGs with the cropped versions so downstream
    # consumers (macos-desktop Swift, halfblock renderer) see consistent art.
    from tpet.art.process import crop_frames_to_common_bbox

    frames = crop_frames_to_common_bbox(frames)
    logger.debug("Union-cropped %d frames to %dx%d", len(frames), frames[0].width, frames[0].height)
    for i, frame in enumerate(frames):
        out_path = art_dir / f"{safe_name}_frame_{i}.png"
        frame.save(out_path, format="PNG")

    result.usage = total_usage
    result.frame_count = len(frames)
    return frames, result


def generate_halfblock_art_openai(
    config: TpetConfig,
    pet: PetProfile,
    on_progress: Callable[[int, int, str], None] | None = None,
    base_image_path: Path | None = None,
) -> tuple[list[str], GenerationResult | None]:
    """Generate half-block art frames via OpenAI with native transparency.

    Args:
        config: Application configuration.
        pet: Pet profile.
        on_progress: Optional callback(current, total, label) for progress updates.
        base_image_path: Optional path to a user-provided idle frame image.

    Returns:
        Tuple of (list of halfblock strings, GenerationResult or None on failure).
    """
    from tpet.art.process import image_to_halfblock, resize_for_halfblock

    frames, gen_result = _generate_openai_frames(
        config,
        pet,
        on_progress=on_progress,
        base_image_path=base_image_path,
    )
    hblk_frames = _process_frames(
        frames,
        config,
        pet.name,
        resize_fn=resize_for_halfblock,
        target_height=config.halfblock_size,
        convert_fn=image_to_halfblock,
        save_fn=save_halfblock_frame,
        label="Halfblock",
        save_png=True,
    )
    return hblk_frames, gen_result


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def generate_art(
    config: TpetConfig,
    pet: PetProfile,
    on_progress: Callable[[int, int, str], None] | None = None,
    base_image_path: Path | None = None,
) -> tuple[list[str], GenerationResult | None]:
    """Generate graphical art based on config settings.

    Dispatches to the appropriate generator based on art_mode and the resolved
    image art provider.  When ``base_image_path`` is provided, the OpenAI-compatible
    pipeline is always used (regardless of provider) since only the OpenAI images
    edit API supports image editing.

    Args:
        config: Application configuration.
        pet: Pet profile.
        on_progress: Optional callback(current, total, label) for progress updates.
        base_image_path: Optional path to a user-provided idle frame image.
            When set, this image is used as frame 0 and OpenAI edit generates variants.

    Returns:
        Tuple of (list of art strings, GenerationResult or None).

    Raises:
        ValueError: If art_mode is not a graphical mode, provider is unsupported,
            or API key is missing.
    """
    from tpet.config import ArtMode, LLMProvider

    resolved = config.resolved_image_art_provider

    # Providers that cannot generate images
    if resolved.provider == LLMProvider.OLLAMA:
        raise ValueError(
            "Ollama does not support image generation. "
            "Set image_art_provider_config.provider to 'openai', 'openrouter', or 'gemini'."
        )
    if resolved.provider == LLMProvider.CLAUDE:
        raise ValueError(
            "Claude does not support image generation via this pipeline. "
            "Set image_art_provider_config.provider to 'openai', 'openrouter', or 'gemini'."
        )

    # Validate API key before dispatching
    if not resolved.api_key:
        config_dir = config.pet_data_dir
        raise ValueError(
            f"API key not found (checked env var: {resolved.api_key_env!r}). "
            f"Image generation via {resolved.provider.value} requires this key.\n"
            f"Set it in your environment or add it to {config_dir / '.env'}"
        )

    # Determine pipeline: OpenAI-compatible (openai/openrouter) or Gemini
    # Force OpenAI-compatible pipeline when a base image is provided
    use_openai_compat = resolved.is_openai_compat or base_image_path is not None

    if config.art_mode == ArtMode.SIXEL_ART:
        if use_openai_compat:
            return generate_halfblock_art_openai(
                config,
                pet,
                on_progress=on_progress,
                base_image_path=base_image_path,
            )
        return generate_halfblock_art(config, pet), None
    if config.art_mode == ArtMode.MACOS_DESKTOP:
        return generate_macos_desktop_art(
            config,
            pet,
            on_progress=on_progress,
            base_image_path=base_image_path,
        )
    raise ValueError(f"Cannot generate graphical art for mode: {config.art_mode}")
